# Fictional Army - Filtering and Sorting

In [19]:
import pandas as pd

### Step 2. This is the data given as a dictionary

In [20]:
# Create an example dataframe about a fictional army
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

### Step 3. Create a dataframe and assign it to a variable called army.

In [21]:
army = pd.DataFrame({
            'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']
})

army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine
5,Dragoons,1st,234,7,1006,37,1,1,4,Iowa
6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,Dragoons,2nd,62,3,849,48,3,1,31,Washington
8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming
10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

### Step 4. Set the 'origin' colum as the index of the dataframe

In [22]:
army.set_index("origin", inplace=True)   #origin esta como indice

army

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Step 5. Print only the column veterans

In [24]:
army["veterans"]

origin
Arizona         1
California      5
Texas          62
Florida        26
Maine          73
Iowa           37
Alaska        949
Washington     48
Oregon         48
Wyoming       435
Louisana       63
Georgia       345
Name: veterans, dtype: int64

### Step 6. Print the columns 'veterans' and 'deaths'

In [14]:
army[["veterans", "deaths"]]

    veterans  deaths
0          1     523
1          5      52
2         62      25
3         26     616
4         73      43
5         37     234
6        949     523
7         48      62
8         48      62
9        435      73
10        63      37
11       345      35

### Step 7. Print the name of all the columns.

In [25]:
army.info()

army.head(0)

print()
list(army.columns)

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, Arizona to Georgia
Data columns (total 9 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   regiment   12 non-null     object
 1   company    12 non-null     object
 2   deaths     12 non-null     int64
 3   battles    12 non-null     int64
 4   size       12 non-null     int64
 5   veterans   12 non-null     int64
 6   readiness  12 non-null     int64
 7   armored    12 non-null     int64
 8   deserters  12 non-null     int64
dtypes: int64(7), object(2)
memory usage: 1.2+ KB

['regiment',
 'company',
 'deaths',
 'battles',
 'size',
 'veterans',
 'readiness',
 'armored',
 'deserters']

### Step 8. Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska

In [17]:
army.loc[army["origin"].isin(["Maine", "Alaska"]), ["deaths", "size", "deserters"]]

   deaths  size  deserters
4      43  1592          3
6     523   987         24

### Step 9. Select the rows 3 to 7 and the columns 3 to 6

In [20]:
army.iloc[2:7, 2:6]

   deaths  battles  size  veterans
2      25        2  1099        62
3     616        2  1400        26
4      43        4  1592        73
5     234        7  1006        37
6     523        8   987       949

### Step 10. Select every row after the fourth row and all columns

In [ ]:
army.iloc[4:]   #o [4::,::]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine
5,Dragoons,1st,234,7,1006,37,1,1,4,Iowa
6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,Dragoons,2nd,62,3,849,48,3,1,31,Washington
8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming
10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

### Step 11. Select every row up to the 4th row and all columns

In [22]:
army.iloc[:4]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida

### Step 12. Select the 3rd column up to the 7th column

In [23]:
army.iloc[:, 2:7]

    deaths  battles  size  veterans  readiness
0      523        5  1045         1          1
1       52       42   957         5          2
2       25        2  1099        62          3
3      616        2  1400        26          3
4       43        4  1592        73          2
5      234        7  1006        37          1
6      523        8   987       949          2
7       62        3   849        48          3
8       62        4   973        48          2
9       73        7  1005       435          1
10      37        8  1099        63          2
11      35        9  1523       345          3

### Step 13. Select rows where df.deaths is greater than 50

In [26]:
army[army["deaths"] > 50][["deaths"]]   #comparación crea booleanos y comparamos

            deaths
origin
Arizona        523
California      52
Florida        616
Iowa           234
Alaska         523
Washington      62
Oregon          62
Wyoming         73

### Step 14. Select rows where df.deaths is greater than 500 or less than 50

In [27]:
army[(army["deaths"] > 500) | (army["deaths"] < 50)][["deaths"]]

          deaths
origin
Arizona      523
Texas         25
Florida      616
Maine         43
Alaska       523
Louisana      37
Georgia       35

### Step 15. Select all the regiments not named "Dragoons"

In [26]:
army[army["regiment"] != "Dragoons"]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming
10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

### Step 16. Select the rows called Texas and Arizona

In [31]:
army[army["origin"].isin(["Texas", "Arizona"])]

print()

army.loc[["Texas", "Arizona"]]   #otra forma

KeyError: 'origin'

### Step 17. Select the third cell in the row named Arizona

In [37]:
army.loc[army["origin"] == "Arizona"].iloc[0, 2]


print(army.loc["Arizona"].iloc[2])

KeyError: 'origin'

### Step 18. Select the third cell down in the column named deaths

In [34]:
army["deaths"].iloc[2]

np.int64(25)