# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [ ]:
import pandas as pd
import numpy as np
import numpy as np

ImportError: DLL load failed while importing sparse: Una directiva de Control de aplicaciones bloqueó este archivo.

In [6]:
pd.__version__

NameError: name 'pd' is not defined

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [3]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 3. Name of the max valued product

In [4]:
pd.__version__

'2.1.4'

In [16]:
chipo["item_price"] = pd.to_numeric(
    chipo["item_price"].astype(str).str.replace("$", ""),  #esta por defecto, no es necesario poner regex=False
    errors="coerce"    #cuando se encuentra con un error pone un NaN
)

,order_id,quantity,item_name,choice_description,item_price,unit_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,3,1,Side of Chips,NaN,1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25

In [17]:

chipo.nlargest(1, "item_price")["item_name"]

3598    Chips and Fresh Tomato Salsa
Name: item_name, dtype: object

In [18]:


chipo["unit_price"] = chipo["item_price"] / chipo["quantity"]  #para sacar el precio unitario que no estaba en el dataset

chipo.head(10) #para ver los primeros 10

,order_id,quantity,item_name,choice_description,item_price,unit_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
6,3,1,Side of Chips,NaN,1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25,9.25

In [19]:


chipo.nlargest(1, "unit_price")[["item_name", "unit_price"]]

            item_name  unit_price
281  Steak Salad Bowl       11.89

### Step 4. How many products cost more than $10.00?

In [21]:
chipo[chipo["unit_price"] > 10.00][["item_name", "item_price"]]


#unique devuelve un listado de valores
#nunique devuelve un numero

               item_name  item_price
4           Chicken Bowl       16.98
5           Chicken Bowl       10.98
7          Steak Burrito       11.75
13          Chicken Bowl       11.25
23       Chicken Burrito       10.98
...                  ...         ...
4610       Steak Burrito       11.75
4611      Veggie Burrito       11.25
4617       Steak Burrito       11.75
4618       Steak Burrito       11.75
4619  Chicken Salad Bowl       11.25

[1130 rows x 2 columns]

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [20]:
precio = chipo["item_price"]

precio = pd.to_numeric(precio.str.replace("$", "", regex=False).str.strip())    #to_numeric para convertir la columna a números, similar astype

pedidos = chipo.loc[precio > 10, "order_id"].nunique()

print(pedidos)

print()

#puedo hacer tambien 
chipo.loc[precio > 10, "order_id"].nunique()

863

863

In [30]:
#esta es la correcta solución del ejercicio

precio = chipo["item_price"]

precio_unitario = precio / chipo["quantity"]

pedidos = chipo.loc[precio_unitario > 10, "order_id"].nunique()
print(pedidos)

print()

#otra forma de hacerlo
print(chipo.loc[(chipo["item_price"] / chipo["quantity"]) > 10, "order_id"].nunique())

787

787

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [36]:
precio = chipo["item_price"]  #astype convierte los precios de texto a números decimales

totales_por_pedido = precio.groupby(chipo["order_id"]).sum()   #uso groupby para agrupar filas x num de pedido   "es como un buble el groupby"

print((totales_por_pedido > 10).sum())


print()

#puedo hacer asi tambien porque ya tengo la columna precio
print((precio.groupby(chipo["order_id"]).sum() > 10).sum())

1834

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [40]:
chipo.loc[precio > 10, "order_id"].nunique()

863

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [21]:
chipo["unit_price"] = precio / chipo["quantity"]   #quantity para obtener el precio por unidad
chipo[["item_name", "unit_price"]].drop_duplicates()   #para quitar las filas repetidas

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
3989                          Chicken Salad        8.19
4235                           Chicken Bowl        8.50
4237                    Chips and Guacamole        4.25
4509                                  Chips        1.99
4510                          Barbacoa Bowl       11.49

[139 rows x 2 columns]

### Step 6. Sort by the name of the item

In [41]:
chipo[["item_name", "unit_price"]].drop_duplicates().sort_values("item_name")   #para ordenar por nombre del producto


chipo_ordenado = chipo.sort_values(by='item_name')  #esta la solución de clase   (es mejor usar el by para estar seguros de que esta ordenando por eso)
chipo_ordenado

,order_id,quantity,item_name,choice_description,item_price,unit_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49,6.49
...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [26]:
chipo.loc[precio.idxmax(), ["item_name", "quantity", "item_price"]]  #busca la fila del precio máximo

item_name     Chips and Fresh Tomato Salsa
quantity                                15
item_price                         $44.25
Name: 3598, dtype: object

In [25]:
chipo.assign(precio=precio).sort_values("precio", ascending=False).iloc[0][    #ordena de mayor a menor y tomar la primera fila
    ["item_name", "quantity", "item_price"]
]

item_name     Chips and Fresh Tomato Salsa
quantity                                15
item_price                         $44.25
Name: 3598, dtype: object

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [ ]:
chipo[chipo["item_name"] == "Veggie Salad Bowl"].shape[0]    #shape devuelve las dimensiones de una tabla como una pareja: (filas, columnas). El [0] selecciona el primer valor, es decir, el número de filas.

18

### Step 9. How many times did someone order more than one Canned Soda?

In [ ]:

#chipo[(chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1)].shape[0]

chipo.loc[
    (chipo["item_name"] == "Canned Soda") & (chipo["quantity"] > 1),   #solucion de clase correcta porque hay alguien que pidio dos veces y por eso tenia 20 como resultado con las otras formas
    "order_id"
].nunique()

#len(chipo.query('item_name == "Canned Soda" and quantity > 1'))  #otra forma: cuenta las filas de Canned Soda donde se pidieron más de una unidad

18